### ISSUE TITLE
Inconsistency between how Medusa and Echidna manage libraries.

### ISSUE THREAD

**Issue by beirao** [crytic/medusa#529]
After successfully setting up a test suite with Echidna, I’ve been trying to integrate Medusa for further testing. However, I’ve run into configuration issues that I suspect are causing the setup to fail.

### Here is my Echidna configuration file, which works perfectly:

```yaml
seqLen: 100
testLimit: 4000
workers: 10
coverage: true
corpusDir: "echidna-corpus"
testMode: assertion
deployer: "0x10000"
sender: ["0x10000", "0x20000", "0x30000"]
coverageFormats: ["txt"]
shrinkLimit: 2000
quiet: true
maxTimeDelay: 3600 # 1 hour
maxBlockDelay: 864
filterBlacklist: true
filterFunctions: []
codeSize: 0xffffffff
cryticArgs: [
  "--compile-libraries=(BorrowLogic,0xf01),(DepositLogic,0xf03),(FlashLoanLogic,0xf11),(GenericLogic,0xf12),(LiquidationLogic,0xf13),(MiniPoolBorrowLogic,0xa01),(MiniPoolDepositLogic,0xa03),(MiniPoolFlashLoanLogic,0xa11),(MiniPoolGenericLogic,0xa12),(MiniPoolLiquidationLogic,0xa13),(MiniPoolReserveLogic,0xa15),(MiniPoolValidationLogic,0xa16),(MiniPoolWithdrawLogic,0xa17)"
]
deployContracts: [
  ["0xf01", "BorrowLogic"],
  ["0xf03", "DepositLogic"],
  ["0xf11", "FlashLoanLogic"],
  ["0xf12", "GenericLogic"],
  ["0xf13", "LiquidationLogic"],
  ["0xa01", "MiniPoolBorrowLogic"],
  ["0xa03", "MiniPoolDepositLogic"],
  ["0xa11", "MiniPoolFlashLoanLogic"],
  ["0xa12", "MiniPoolGenericLogic"],
  ["0xa13", "MiniPoolLiquidationLogic"],
  ["0xa15", "MiniPoolReserveLogic"],
  ["0xa16", "MiniPoolValidationLogic"],
  ["0xa17", "MiniPoolWithdrawLogic"]
]
```

### Here is my Medusa configuration file:

```json
{
	"fuzzing": {
	  "workers": 10,
	  "workerResetLimit": 50,
	  "timeout": 0,
	  "testLimit": 0,
	  "shrinkLimit": 5000,
	  "callSequenceLength": 100,
	  "corpusDirectory": "",
	  "coverageEnabled": true,
	  "targetContracts": [],
	  "predeployedContracts": {
		  "BorrowLogic": "0xf01",
		  "DepositLogic": "0xf03",
		  "FlashLoanLogic": "0xf11",
		  "GenericLogic": "0xf12", 
		  "LiquidationLogic": "0xf13",

		  "MiniPoolBorrowLogic": "0xa01",
		  "MiniPoolDepositLogic": "0xa03",
		  "MiniPoolFlashLoanLogic": "0xa11",
		  "MiniPoolGenericLogic": "0xa12",
		  "MiniPoolLiquidationLogic": "0xa13",
		  "MiniPoolReserveLogic": "0xa15",
		  "MiniPoolValidationLogic": "0xa16",
		  "MiniPoolWithdrawLogic": "0xa17"
	  },
	  "targetContractsBalances": [],
	  "constructorArgs": {},
	  "deployerAddress": "0x30000",
	  "senderAddresses": ["0x10000", "0x20000", "0x30000"],
	  "blockNumberDelayMax": 60480,
	  "blockTimestampDelayMax": 604800,
	  "blockGasLimit": 125000000,
	  "transactionGasLimit": 12500000,
	  "testing": {
		"stopOnFailedTest": true,
		"stopOnFailedContractMatching": false,
		"stopOnNoTests": true,
		"testAllContracts": false,
		"traceAll": false,
		"assertionTesting": {
		  "enabled": true,
		  "testViewMethods": false,
		  "panicCodeConfig": {
			"failOnCompilerInsertedPanic": false,
			"failOnAssertion": true,
			"failOnArithmeticUnderflow": false,
			"failOnDivideByZero": false,
			"failOnEnumTypeConversionOutOfBounds": false,
			"failOnIncorrectStorageAccess": false,
			"failOnPopEmptyArray": false,
			"failOnOutOfBoundsArrayAccess": false,
			"failOnAllocateTooMuchMemory": false,
			"failOnCallUninitializedVariable": false
		  }
		},
		"propertyTesting": {
		  "enabled": true,
		  "testPrefixes": ["property_"]
		},
		"optimizationTesting": {
		  "enabled": true,
		  "testPrefixes": ["optimize_"]
		},
		"targetFunctionSignatures": [],
		"excludeFunctionSignatures": []
	  },
	  "chainConfig": {
		"codeSizeCheckDisabled": true,
		"cheatCodes": {
		  "cheatCodesEnabled": true,
		  "enableFFI": false
		},
		"skipAccountChecks": true
	  }
	},
	"compilation": {
	  "platform": "crytic-compile",
	  "platformConfig": {
		"target": "../../../contracts",
		"solcVersion": "",
		"exportDirectory": "",
		"args": [
			"--foundry-compile-all",
			"--compile-libraries=(BorrowLogic,0xf01),(DepositLogic,0xf03),(FlashLoanLogic,0xf11),(GenericLogic,0xf12),(LiquidationLogic,0xf13),(MiniPoolBorrowLogic,0xa01),(MiniPoolDepositLogic,0xa03),(MiniPoolFlashLoanLogic,0xa11),(MiniPoolGenericLogic,0xa12),(MiniPoolLiquidationLogic,0xa13),(MiniPoolReserveLogic,0xa15),(MiniPoolValidationLogic,0xa16),(MiniPoolWithdrawLogic,0xa17)"
			]	  
		}
	},
	"logging": {
	  "level": "info",
	  "logDirectory": "",
	  "noColor": false
	}
  }
```

When I run the command below, I encounter an error related to the predeployed contracts not being found in the compilation artifacts:

```bash
medusa fuzz --config config/medusa_config2.json
Error Log:
⇾ Reading the configuration file at: config/medusa_config2.json
⇾ Compiling targets with crytic-compile
⇾ Running command:
/opt/homebrew/bin/crytic-compile ../../../contracts --export-format solc --foundry-compile-all --compile-libraries=(BorrowLogic,0xf01),(DepositLogic,0xf03),(FlashLoanLogic,0xf11),(GenericLogic,0xf12),(LiquidationLogic,0xf13),(MiniPoolBorrowLogic,0xa01),(MiniPoolDepositLogic,0xa03),(MiniPoolFlashLoanLogic,0xa11),(MiniPoolGenericLogic,0xa12),(MiniPoolLiquidationLogic,0xa13),(MiniPoolReserveLogic,0xa15),(MiniPoolValidationLogic,0xa16),(MiniPoolWithdrawLogic,0xa17)
⇾ Finished compiling targets in 0s
⇾ Initializing corpus
error Failed to create the test chain
‣ MiniPoolFlashLoanLogic was specified in the predeployed contracts but was not found in the compilation artifacts
```

Interestingly, the library listed as problematic (here MiniPoolFlashLoanLogic) changes with each rerun of the command.

If there are no errors on my end, and the Echidna and Medusa config files are equivalent, then there must be a problem with how Medusa handles libraries.
